class TiledeskChatbotConst {
    
    static REQ_DEPARTMENT_ID_KEY = "department_id";
    static REQ_PROJECT_ID_KEY = "project_id";
    static REQ_REQUEST_ID_KEY = "conversation_id";
    static REQ_CHATBOT_NAME_KEY = "chatbot_name";
    static REQ_CHATBOT_ID_KEY = "chatbot_id";
    static REQ_LAST_USER_TEXT_KEY = "last_user_text";
    static REQ_LAST_USER_TEXT_v2_KEY = "lastUserText";
    static REQ_LAST_MESSAGE_ID_KEY = "last_message_id";
    static REQ_COUNTRY_KEY = "user_country";
    static REQ_CITY_KEY = "user_city";
    static REQ_USER_SOURCE_PAGE_KEY = "user_source_page";
    static REQ_USER_LANGUAGE_KEY = "user_language";
    static REQ_USER_AGENT_KEY = "user_agent";
    static REQ_DEPARTMENT_NAME_KEY = "department_name";
    static REQ_END_USER_ID_KEY = "user_id";
    static REQ_END_USER_IP_ADDRESS_KEY = "user_ip_address";
    static REQ_CHAT_URL = "chat_url";
    static REQ_LAST_USER_MESSAGE_TYPE_KEY = "lastUserMessageType";
    static REQ_TRANSCRIPT_KEY = "transcript";
    static REQ_LAST_USER_MESSAGE_KEY = "lastUserMessage";
    static REQ_CHAT_CHANNEL = "chatChannel";
    static REQ_DECODED_JWT_KEY = "decodedCustomJWT";
    static REQ_REQUESTER_IS_AUTHENTICATED_KEY = "strongAuthenticated";
    static USER_INPUT = "_userInput";
    static REQ_LEAD_USERFULLNAME_KEY = "userFullname";
    static REQ_LEAD_EMAIL_KEY = "userEmail";
    static REQ_USER_PHONE_KEY = "userPhone";
    static REQ_CURRENT_PHONE_NUMBER_KEY = "currentPhoneNumber";
    static REQ_USER_LEAD_ID_KEY = "userLeadId";
    static REQ_USER_COMPANY_KEY = "userCompany";
    static REQ_TICKET_ID_KEY = "ticketId";
    static REQ_CHATBOT_TOKEN = "chatbotToken";
    static REQ_CHATBOT_TOKEN_v2 = "chatbot_jwt_token";
    static API_BASE_URL = "api_base_url";
    static REQ_LAST_USER_IMAGE_URL = 'lastUserImageURL';
    static REQ_LAST_USER_IMAGE_NAME = 'lastUserImageName';
    static REQ_LAST_USER_IMAGE_WIDTH = 'lastUserImageWidth';
    static REQ_LAST_USER_IMAGE_HEIGHT = 'lastUserImageHeight';
    static REQ_LAST_USER_IMAGE_TYPE = 'lastUserImageType';
    static REQ_LAST_USER_DOCUMENT_URL = 'lastUserDocumentURL';
    static REQ_LAST_USER_DOCUMENT_NAME = 'lastUserDocumentName';
    static REQ_LAST_USER_DOCUMENT_TYPE = 'lastUserDocumentType';
    static REQ_EMAIL_ATTACHMENTS_LINK = 'link';
    static REQ_EMAIL_SUBJECT = 'email_subject';
    static REQ_EMAIL_TO = 'email_toEmail';
    static REQ_EMAIL_FROM = 'email_fromEmail';
    static REQ_EMAIL_MESSAGE_ID = 'email_messageId';
    static REQ_EMAIL_REPLY_TO = 'email_replyTo';
    static REQ_EMAIL_EML = 'email_eml';
    static REQ_EMAIL_ATTACHMENTS_FILES = 'attachments'
}

module.exports = { TiledeskChatbotConst };